export const ADD_COMMENT = 'ADD_COMMENT';
export const DISHES_LOADING = 'DISHES_LOADING';
export const DISHES_FAILED = 'DISHES_FAILED';
export const ADD_DISHES = 'ADD_DISHES';

export const ADD_FINALTESTS = 'ADD_FINALTESTS';
export const FINALTESTS_LOADING = 'FINALTESTS_LOADING';
export const FINALTESTS_FAILED = 'FINALTESTS_FAILED';

export const ADD_DOWNLOADS = 'ADD_DOWNLOADS';
export const DOWNLOADS_LOADING = 'DOWNLOADS_LOADING';
export const DOWNLOADS_FAILED = 'DOWNLOADS_FAILED';

export const ADD_RECORDS = 'ADD_RECORDS';
export const RECORDS_FAILED = 'RECORDS_FAILED';
export const RECORDS_LOADING = 'RECORDS_LOADING';
export const ADD_RANKS = 'ADD_RANKS';
export const RANKS_FAILED = 'RANKS_FAILED';
export const RANKS_LOADING = 'RANKS_LOADING';
export const ADD_COMMENTS = 'ADD_COMMENTS';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';
export const PROMOS_LOADING = 'PROMOS_LOADING';
export const ADD_PROMOS = 'ADD_PROMOS';
export const PROMOS_FAILED = 'PROMOS_FAILED';
export const LEADERS_LOADING = 'LEADERS_LOADING';
export const ADD_LEADERS = 'ADD_LEADERS';
export const LEADERS_FAILED = 'LEADERS_FAILED';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
export const FAVORITES_LOADING = 'FAVORITES_LOADING';
export const FAVORITES_FAILED = 'FAVORITES_FAILED';
export const ADD_FAVORITES = 'ADD_FAVORITES';
